### PR TITLE
Add discordimages.com as a domain

### PR DESCRIPTION
**Pull request by iilukas**

### CODE REVIEW

**Comment by theLMGN** [comment]
@Pitu I have a slight issue with this, because DiscordImages is breaking your licence, and Luca is extremely childlike, image and blogpost from @gtsatsis 
image
https://blog.ratelimited.me/my-personal-experience-with-discordimages/

**Comment by PascalTemel** [comment]
Yikes

**Comment by gtsatsis** [comment]
@BobbyWibowo, Yeah, that is the alt of Luca. They sued someone over leaking their fork of Lolisafe, by the way. (Mentioned in the blog post)

**Comment by Pitu** [comment]
Didn't realize it was Luca until you brought it to my attention https://lolisafe.moe/XrCCm0FQ.png

**Comment by theLMGN** [comment]
So, what are the expected outcomes of resolving this problem?

**Comment by gtsatsis** [comment]
@Pitu I'd also like you to take note of this message from Luca, lying to their users about having a deal with you regarding it. https://dj-electro.me/808207.png

**Comment by iamluca** [comment]
Hi there! We are now following the license check https://discordimages.com/faq 

I don’t want any issues between Discord Images and lolisafe. I hope we have resolved this. Can we confirm if this is resolved?

**Comment by theLMGN** [comment]
Also, I seem to have been banned from the Discord Images discord server, and all I said was "hey"

**Comment by iamluca** [comment]
We want nothing to do with RATELIMITED

**Comment by theLMGN** [comment]
I am not affliliated with RL. I am simply in their Discord server, and have used their services in the past. I don't, even if I was affiliated with RL, to simply ban me for the word "hey"

**Comment by Pitu** [comment]
#177

**Pull request merged**
