### PR TITLE
Another Docker support...however

### PR DESCRIPTION
**Pull request by Icemic**
Well, there's a "Docker support" PR already, for which I had to say sorry to @kevinvdburgt . 
I did not check PR page, until I had done nearly all of the work.

### CODE REVIEW

**Comment by iCrawl** [comment]
Lets not use nodemon for this thank you, nodemon is for development purpose only.

**Comment by Icemic** [comment]
Done.

**Comment by kevinvdburgt** [comment]
Completely forgot about this project.. Lets use your PR instead :)

**Comment by Icemic** [comment]
@kevinvdburgt thx

And, I find there's a critical bug when using Docker, which can causes crashes. Don't merge this pr until I solve it. It seems to do with the mounting of db file.

**Comment by Icemic** [comment]
Solved.

We have to use debian instead of alpine. Node with alpine always crashes without any log.

Possible reason: https://hub.docker.com/_/node/
> The main caveat to note is that it does use musl libc instead of glibc and friends, so certain software might run into issues depending on the depth of their libc requirements. 

Sqlite3 support depends on libc.

**Comment by iCrawl** [comment]
Added in 8a75ab91

**Pull request closed without merging**
