### PR TITLE
Patch to allow "retries" when generating random name

### PR DESCRIPTION
**Pull request by BobbyWibowo**
Looks good? I was debating on whether I should use 3 tries or 1 try for the default value, but in the end I decided to go with 1 try as to "sort of" follow the old behavior. Though technically speaking, the old behavior was to replace the old file, but in here it would return an error instead.

Also the comments in the config file could probably be phrased better but I'm having a mental block atm.

Other than that, do you mind sharing your eslint config file or something? I had to turn off 27 rules (28 including func-names in the package.json file) just so that none of the JS files show any errors/warnings. Though I can't really be sure whether it was my eslint not being setup properly or something ~~(*cough*, standard master race)~~.

### CODE REVIEW

**Comment by iCrawl** [comment]
I think fsstat should be used here to check whether a file is already there or not, apart from that it looks fine.
I'm sure there's other and better ways to handle this topic, but this will certainly do for a while.

**Comment by BobbyWibowo** [comment]
Node.js docs kinda said in the description for fs.stat():
> To check if a file exists without manipulating it afterwards, fs.access() is recommended.

and I was like, "that sounds exactly like what I want it to do", since after all it's not supposed to manipulate any of the existing files, so then I was like, "well, fs.access() it is then!".
ref: https://nodejs.org/api/fs.html#fs_fs_stat_path_callback
I'm guessing it's because fs.stats() will return an fs.Stats object with a bunch of information of the file, but we kinda don't really need that for this (?).

**Comment by iCrawl** [comment]
I blame node docs for this, seriously. The way they phrase certain things, if you look at the "recommended" approach for fs.access they also mention its not recommended to use for certain actions.

Anyway, thanks, yea should be fine. Though should this really be a sync process? We gotta consider we are in a single-threaded env with an event-loop here. If you upload 20 or more files, and so do other users at the same time, this can certainly bite you in the butt, no?

**Comment by BobbyWibowo** [comment]
At first I thought turning the filename function into async and promisifying fs.access would not work, for some reason, so I went with sync function, but apparently it would actually work.

So yeah, I did some experimenting and first I went with turning filename function into an async function and promisifying fs.access:
```js
  filename: async function (req, file, cb) {
    for (let i = 0; i < maxTries; i++) {
      const name = randomstring.generate(config.uploads.fileLength) + path.extname(file.originalname)
      const fileNotExists = await accessPromisified(path.join(uploadDir, name)).catch(() => true)
      if (fileNotExists) return cb(null, name)
      console.log(`A file named "${name}" already exists (${i}/${maxTries}).`)
    }
    return cb('Could not allocate a unique file name. Try again?')
  }
```

but eslint didn't really like me having an await in a loop (although it was just a warning really), so I kinda came up with uh.. calling itself over and over:
```js
  filename: function (req, file, cb) {
    const access = i => {
      const name = randomstring.generate(config.uploads.fileLength) + path.extname(file.originalname)
      fs.access(path.join(uploadDir, name), err => {
        if (err) return cb(null, name)
        if (++i < maxTries) return access(i)
        console.log(`A file named "${name}" already exists (${i}/${maxTries}).`)
        return cb('Could not allocate a unique file name. Try again?')
      })
    }
    access(0)
  }
```

Actually I don't really understand much this whole callback thingies.
Anyways, both works. I can't be sure which one is better than the other, so eh, you choose? kek

**Comment by iCrawl** [comment]
While the rule "no-await-in-loop" certainly is just a warning, for the matter of fact telling you "are you really sure you want an await in here, it will potentially slow down execution" and it should be taken as such. It is only a rule that hints at you (like really, anything else in eslint) asking if you are sure what you are doing. You might not want to await stuff in a for loop in certain cases but you might forget that you are in one (lets consider a very big loop with lots of execution) this can certainly happen.

For the second thing, I probably would prefer the callback route here, since this is the so-called "real async" way. You aren't really awaiting anything so the execution is not "paused" (blocking would be the wrong word here because when awaiting something you "hold" execution only in function scope).

**Comment by BobbyWibowo** [comment]
Thanks~

On a side note, I really need help with the eslint config, sheesh. Some JS files doesn't even have semicolons on some places, but since that is exactly how it is in the repo, it's driving me insane (one example: https://github.com/WeebDev/lolisafe/blob/master/controllers/albumsController.js#L26).

**Comment by Pitu** [comment]
I'll make sure to fix all the eslint stuff and include the eslint config I'm currently using as standard. Thanks for this!

**Pull request merged**
