### PR TITLE
Formatting + readme adjustment

### PR DESCRIPTION
**Pull request by robflop**
While doing some modifications for my own instance (replacing icons), I noticed that the formatting wasn't consistent across all files, so I changed that.

Also changed one instance of "loli-safe" being used rather than "lolisafe" -- I saw a commit in the chrome extension's repo that went along the lines of "Change loli-safe to lolisafe" so I assume it's already been changed to say this in the menu.

### CODE REVIEW

**Comment by RyoshiKayo** [comment]
Kana is rewriting lolisafe and is should release in the next century or so

**Comment by robflop** [comment]
rip, understandable though

**Comment by Shumatsu** [comment]
I didn't change that instance of "loli-safe" in #77 before, because extension was still using it. And then I forgot.

**Comment by Pitu** [comment]
It's fine, already taken care of. Just a few more days and the new version branch will be there for testing and bug hunting.

**Pull request closed without merging**
