### PR TITLE
Site list revision

### PR DESCRIPTION
**Pull request by Shumatsu**
- UPDX - uses SSL, so no need to keep http: link.
- Kayo.pics - redirects to kayo.moe
- safe.waliant.pw - entire waliant.pw is down right now.
- a.hyper.lol - added a space because I don't like when words are unnecessarily mashed together.

### CODE REVIEW

**Comment by Shumatsu** [comment]
@VVLNT I'm not sure if I just hit a downtime. Is the site still operating?

**Comment by VVLNT** [comment]
@Shumatsu Yes, it's up now. It was a mistake on my part which caused my webserver to not start.

**Comment by Shumatsu** [comment]
I have restored waliant.pw on the list. PR is ready to go.

**Comment by VVLNT** [comment]
[https://updx.xyz](updx.xyz) doesn't seem to be using lolisafe anymore.

**Comment by Shumatsu** [comment]
Thanks for mentioning, didn't realize at first.

**Comment by Pitu** [comment]
Sounds good

**Pull request merged**
