### PR TITLE
Add new site

### PR DESCRIPTION
**Pull request by ImUrX**
I site I made 3 months ago, I think it's okay now for it to be here.

### CODE REVIEW

**Comment by RyoshiKayo** [comment]
IMO You shouldn't add your site to the front of a project until it's at least completed..

**Comment by ImUrX** [comment]
i was talking about the site itself, i havent finished the 2dgirls.date part, only the image hosting

**Comment by RyoshiKayo** [comment]
Then you subdomain wouldn't be a WIP then 🤔 
Just put a splash page on your main domain.

**Comment by ImUrX** [comment]
OK, i will do that

oh btw u r the one who mantains the debian package no?
https://github.com/WeebDev/lolisafe-deb/issues/1

**Comment by ImUrX** [comment]
i know but i wanted to notify you ;-;

**Comment by Pitu** [comment]
@ImUrX Can you please join the Discord support server? We noticed you are using Amazon EC2 and that's a terrible idea and would like to offer some suggestions.

**Pull request merged**
