### PR TITLE
added dmca.gripe

### PR DESCRIPTION
**Pull request by Danny240**
dmca.gripe allows for censorship-free and permanent filehosting on-top of lolisafe.

### CODE REVIEW

**Comment by alucard0134** [comment]
inetnum:         188.209.52.0 - 188.209.52.255
netname:         BlazingFast
>blazingfast

kek'd

**Comment by Danny240** [comment]
@alucard0134 It's just a proxy to bypass cloudflare's 200MB limit. Blazingfast doesn't sell 10TB servers iirc.

**Comment by alucard0134** [comment]
okay now you made me try a little

89.40.5.55 (1c8b.f.time4vps.cloud)
 Summary   WHOIS ​  Raw Data
Basic Information
OS
Ubuntu
Network
RACKRAY UAB Rakrejus (LT)
Routing
89.40.0.0/20 via AS7018 , AS174 , AS13194 , AS62282
Protocols
80/HTTP, 22/SSH, 25/SMTP
80/HTTP
 
GET /
Server
nginx 1.10.3
Status Line
200 OK
Page Title
dmca.gripe - censorship-free file hosting
GET /

and i looked at this "time4vps" domain your PTR is set to, they dont seem to offer 10TB hdd, with unmetered gbit, but id be happy to recommend ovh, to which they provide unmetered networking and 8TB of storage for me :)

**Comment by Danny240** [comment]
Well, gbit port speed and 40TB of bandwidth pretty much the same as unmetered really, only difference being its actually metered.

As for OVH, I'm not going to send my ID to some $15/hour support agent to buy a server for a site that essentially is a backup for peoples gay porn images

**Comment by alucard0134** [comment]
well if you funnel OVH enough money they wont worry :) but i go thru 40TB in a week so unfortunately that isnt an option for me

**Pull request merged**
